// frontend/src/components/dialogs/translation-cell-dialog.tsx
'use client';

import { useState } from 'react';
import { dto } from '@/wailsjs/go/models';
import { SOURCE_LANG } from '@/lib/ffx/save-all';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { GameTextEditor } from '@/components/editor/game-text-editor';

export interface TranslationCellDialogProps {
  open: boolean;
  row: dto.TextRow | null;
  /** Idiomas de consulta, sem o idioma de origem (us). */
  languages: Array<{ code: string; name: string }>;
  /** Fechamento: value != undefined aplica a edição. */
  onClosed: (value?: string) => void;
}

export function TranslationCellDialog({
  open,
  row,
  languages,
  onClosed,
}: TranslationCellDialogProps) {
  // Remontado por key no pai a cada linha: o state inicial já reflete a linha.
  const [text, setText] = useState(row?.text?.[SOURCE_LANG] ?? '');

  const original = row?.text?.[SOURCE_LANG] ?? '';

  const changed = text !== original;
  const referenceLangs = languages.filter((l) => l.code !== SOURCE_LANG);

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        if (!o) onClosed();
      }}
    >
      <DialogContent className="sm:max-w-[720px] max-h-[90vh] flex flex-col">
        <DialogHeader>
          <DialogTitle>
            Linha #{row?.index}
            {row?.name ? <span className="opacity-70"> · {row.name}</span> : null}
          </DialogTitle>
          <DialogDescription>
            Tradução ({SOURCE_LANG}) — gravada no jogo ao salvar
          </DialogDescription>
        </DialogHeader>

        <div className="flex flex-col gap-4 overflow-hidden">
          <div className="grid gap-2.5 overflow-y-auto flex-1 min-h-[120px] max-h-[42vh] pr-1">
            {referenceLangs.length === 0 ? (
              <p className="opacity-70">Sem outros idiomas nesta linha.</p>
            ) : (
              referenceLangs.map((lang) => (
                <div key={lang.code}>
                  <span className="text-xs font-semibold opacity-75">
                    {lang.name} ({lang.code})
                  </span>
                  <p className="mt-0.5 whitespace-pre-wrap">
                    {row?.text?.[lang.code] ?? '—'}
                  </p>
                </div>
              ))
            )}
          </div>

          <div className="grid gap-1.5">
            <span className="text-xs font-semibold opacity-75">
              Tradução ({SOURCE_LANG}) — gravada no jogo ao salvar
            </span>
            <GameTextEditor value={text} onValueChange={setText} />
          </div>
        </div>

        <DialogFooter>
          <Button variant="ghost" onClick={() => onClosed()}>
            Cancelar
          </Button>
          <Button disabled={!changed} onClick={() => onClosed(text)}>
            Salvar
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// frontend/src/app/editor/translation-cell-dialog/translation-cell-dialog.component.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { dto } from '../../../../wailsjs/go/models';
import { GameTextEditorComponent } from '../game-text/game-text-editor.component';

/** Idioma editado/salvo no "traduzido" (substitui o inglês no binário). */
export const SOURCE_LANG = 'us';

export interface TranslationCellDialogData {
  row: dto.TextRow;
  /** Idiomas de consulta, sem o idioma de origem (us). */
  languages: Array<{ code: string; name: string }>;
}

@Component({
  selector: 'app-translation-cell-dialog',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatDialogModule, GameTextEditorComponent],
  template: `
    <h2 mat-dialog-title>
      Linha #{{ data.row.index }}@if (data.row.name) {
        <span class="row-name"> · {{ data.row.name }}</span>
      }
    </h2>
    <mat-dialog-content>
      <div class="references">
        @for (lang of referenceLangs; track lang.code) {
          <div class="reference">
            <span class="ref-lang">{{ lang.name }} ({{ lang.code }})</span>
            <p class="ref-text">{{ refText(lang.code) }}</p>
          </div>
        } @empty {
          <p class="ref-empty">Sem outros idiomas nesta linha.</p>
        }
      </div>
      <div class="editor-block">
        <span class="editor-label">Tradução ({{ sourceLang }}) — gravada no jogo ao salvar</span>
        <app-game-text-editor
          [value]="text()"
          (valueChange)="onText($event)"
        />
      </div>
    </mat-dialog-content>
    <mat-dialog-actions align="end">
      <button mat-button (click)="cancel()">Cancelar</button>
      <button mat-flat-button color="primary" [disabled]="!changed()" (click)="save()">
        Salvar
      </button>
    </mat-dialog-actions>
  `,
  styles: [
    `
      mat-dialog-content {
        display: flex;
        flex-direction: column;
        overflow: hidden;
      }
      .references {
        display: grid;
        gap: 10px;
        margin-bottom: 16px;
        overflow-y: auto;
        flex: 1 1 auto;
        min-height: 120px;
        max-height: 42vh;
        padding-right: 4px;
      }
      .ref-lang {
        font-size: 12px;
        font-weight: 600;
        opacity: 0.75;
      }
      .ref-text {
        margin: 2px 0 0;
        white-space: pre-wrap;
      }
      .ref-empty {
        opacity: 0.7;
      }
      .editor-block {
        display: grid;
        gap: 6px;
        flex: 0 0 auto;
        overflow: visible;
      }
      .editor-label {
        font-size: 12px;
        font-weight: 600;
        opacity: 0.75;
      }
      .row-name {
        opacity: 0.7;
      }
    `,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TranslationCellDialogComponent {
  readonly data = inject<TranslationCellDialogData>(MAT_DIALOG_DATA);
  private readonly ref = inject(MatDialogRef<TranslationCellDialogComponent>);

  protected readonly sourceLang = SOURCE_LANG;

  protected readonly text = signal(this.data.row.text?.[SOURCE_LANG] ?? '');

  protected readonly changed = signal(
    this.text() !== (this.data.row.text?.[SOURCE_LANG] ?? '')
  );

  protected readonly referenceLangs: ReadonlyArray<{ code: string; name: string }> =
    this.data.languages.filter((l) => l.code !== SOURCE_LANG);

  protected refText(code: string): string {
    return this.data.row.text?.[code] ?? '—';
  }

  protected onText(value: string): void {
    this.text.set(value);
    this.changed.set(value !== (this.data.row.text?.[SOURCE_LANG] ?? ''));
  }

  protected cancel(): void {
    this.ref.close();
  }

  protected save(): void {
    if (!this.changed()) return;
    this.ref.close(this.text());
  }
}
